# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sysmon.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csysmon.proto\"\x07\n\x05\x45mpty\"\x1b\n\tHeartbeat\x12\x0e\n\x06status\x18\x01 \x01(\t\"&\n\x07Metrics\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x02\x12\x0e\n\x06memory\x18\x02 \x01(\x02\"*\n\x0c\x43PUStopwatch\x12\r\n\x05start\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x02\"*\n\x0cNTPStopwatch\x12\r\n\x05start\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x02\x32T\n\x0eMetricsService\x12\x1e\n\nGetMetrics\x12\x06.Empty\x1a\x08.Metrics\x12\"\n\x0cGetHeartbeat\x12\x06.Empty\x1a\n.Heartbeatb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sysmon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=16
  _globals['_EMPTY']._serialized_end=23
  _globals['_HEARTBEAT']._serialized_start=25
  _globals['_HEARTBEAT']._serialized_end=52
  _globals['_METRICS']._serialized_start=54
  _globals['_METRICS']._serialized_end=92
  _globals['_CPUSTOPWATCH']._serialized_start=94
  _globals['_CPUSTOPWATCH']._serialized_end=136
  _globals['_NTPSTOPWATCH']._serialized_start=138
  _globals['_NTPSTOPWATCH']._serialized_end=180
  _globals['_METRICSSERVICE']._serialized_start=182
  _globals['_METRICSSERVICE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
